import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import SideBar from "@/components/SideBar";
import Navbar from "@/components/NavBar";
import MobileBottomNav from "@/components/MobileBottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="flex min-h-screen w-full  bg-gradient-to-b from-[#EEEEEE] to-[#DADADA]">
          <div className="hidden md:block fixed left-0 top-0 h-screen w-[304px] z-20 ">
            <SideBar />
          </div>

          <div className="flex flex-col flex-1 md:ml-[304px] md:mr-[-3px]"> 
            <div className="sticky top-0 z-10 pt-3 px-4 sm:px-6 md:px-8 lg:px-10 md:calc(100%-304px) bg-[#EEEEEE]">
              <Navbar />
            </div>

            <div className="flex-1 overflow-y-auto px-4 sm:px-6 md:px-8 lg:px-10 pb-[100px] md:pb-0">
              {children}
            </div>
          </div>

          <MobileBottomNav />
        </div>
      </body>
    </html>
  );
}


